### ISSUE TITLE
Rarely crashes.

### ISSUE THREAD

**Issue by YuK1Game** [eamodio/vscode-gitlens#1116]
- GitLens Version: v10.2.2
  
- VSCode Version: 1.49.1
- OS Version: Windows 10

Steps to Reproduce:

1. I'm not sure what the procedure is, but the extension crashes after using it for a while.

```
c:\Users\UserName\.vscode\extensions\cesium.gltf-vscode-2.3.1\node_modules\draco3dgltf\draco_decoder_gltf_nodejs.js:9
var Module=typeof DracoDecoderModule!=="undefined"?DracoDecoderModule:{};var isRuntimeInitialized=false;var isModuleParsed=false;Module["onRuntimeInitialized"]=function(){isRuntimeInitialized=true;if(isModuleParsed){if(typeof Module["onModuleLoaded"]==="function"){Module["onModuleLoaded"](Module)}}};Module["onModuleParsed"]=function(){isModuleParsed=true;if(isRuntimeInitialized){if(typeof Module["onModuleLoaded"]==="function"){Module["onModuleLoaded"](Module)}}};function isVersionSupported(versionString){if(typeof versionString!=="string")return false;const version=versionString.split(".");if(version.length<2||version.length>3)return false;if(version[0]==1&&version[1]>=0&&version[1]<=3)return true;if(version[0]!=0||version[1]>10)return false;return true}Module["isVersionSupported"]=isVersionSupported;var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){mo

Error: abort(Git error {
  "exitCode": 128,
  "stdout": "",
  "stderr": "fatal: c:\\Users\\UserName\\Documents\\Projects\\Workspace\\projectname\\.git: 'c:\\Users\\UserName\\Documents\\Projects\\Workspace\\projectname\\.git' is outside repository\n"
}). Build with -s ASSERTIONS=1 for more info.
    at process.abort (c:\Users\UserName\.vscode\extensions\cesium.gltf-vscode-2.3.1\node_modules\draco3dgltf\draco_decoder_gltf_nodejs.js:35:7672)
    at process.emit (events.js:228:7)
    at processEmit [as emit] (c:\Users\UserName\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\node_modules\signal-exit\index.js:155:32)
    at processPromiseRejections (internal/process/promises.js:201:33)
    at processTicksAndRejections (internal/process/task_queues.js:95:32)

```

**Comment by eamodio** [comment]
Does it still happen with GitLens 11? And do you still see the issue if you disable the _glTF Tools_ extension?
