### ISSUE TITLE
Git Lens extension stopped working on latest insiders build

### ISSUE THREAD

**Issue by vvs** [eamodio/vscode-gitlens#118]
- VSCode Version: Code - Insiders 1.15.0-insider (9a308d1128df9af90e84b2988bce4f57f885b1c3, 2017-07-19T06:40:44.535Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|0.15.2
project-manager|ale|0.18.1
vscode-eslint|dba|1.2.11
gitlens|eam|4.3.1
EditorConfig|Edi|0.9.4
beautify|Hoo|1.1.1
atom-keybindings|ms-|2.9.1
stylelint|shi|0.27.0

---

Git Lens doesn't work with the latest insiders build anymore.

Steps to Reproduce:

1. Launch VS Code Insiders with the installed Gitlens extension https://github.com/eamodio/vscode-gitlens/
2. Notice that the extension doesn't work anymore: it doesn't show in the status bar the author of the current line, doesn't show blame output, doesn't provide many of its features in via the command palette.

I bisected the recent VS Code changes and here's the commit that breaks the extension: Microsoft/vscode@531b6b1c219fb4b18df6a429d19ed2649c2c61ac

I've filed a bug against VS Code as well, since I am not sure where the fix should be: Microsoft/vscode/issues/31048

Debug output:
```
[Extension Host] debugger listening on port 5870
/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:301 [Extension Host] [GitLens] GitLens(v4.3.1) active: w:/work/github/vscode.git
/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:301 [Extension Host] [GitLens] Git found: 2.13.3.windows.1.13.gaf0c2223da @ W:\re\git\cmd\git.exe
/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:301 [Extension Host] [GitLens] git -c core.quotepath=false rev-parse --show-toplevel   cwd='w:/work/github/vscode.git'
/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:301 [Extension Host] [GitLens] Git version: 2.13.3.windows.1.13.gaf0c2223da
/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:301 [Extension Host] [GitLens] CodeLens config changed; resetting CodeLens provider
/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:301 [Extension Host] [GitLens] Not Cached(log:n1): getLogForFile('undefined', 'w:\work\github\vscode.git\package.json', undefined, 1, undefined, false)
/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:301 [Extension Host] [GitLens] Add log cache for 'w:/work/github/vscode.git/package.json:log:n1'
2/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:301 [Extension Host] [GitLens] Cached(log:n1): getLogForFile('undefined', 'w:\work\github\vscode.git\package.json', undefined, 1, undefined, false)
/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:301 [Extension Host] [GitLens] git -c core.quotepath=false log --name-status --full-history -M --date=iso8601 --format=%H -%nauthor %an%nauthor-date %ai%nparents %P%nsummary %B%nfilename ? --follow -n1 --no-merges -- package.json   cwd='w:/work/github/vscode.git'
2/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:301 [Extension Host] [GitLens] getRemotes('w:/work/github/vscode.git')
/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:301 [Extension Host] [GitLens] Not Cached(blame): getBlameForFile('w:/work/github/vscode.git/', '', undefined)
/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:301 [Extension Host] [GitLens] Add blame cache for ':blame'
/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:301 [Extension Host] [GitLens] Skipping blame; '' is gitignored
2/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:301 [Extension Host] [GitLens] git -c core.quotepath=false remote -v   cwd='w:/work/github/vscode.git'
/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:301 [Extension Host] [GitLens] Triggering a reset of the git CodeLens provider
/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:301 [Extension Host] [GitLens] Git cache changed; resetting current line annotations
/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:301 [Extension Host] [GitLens] Not Cached(log:n1): getLogForFile('undefined', 'w:\work\github\vscode.git\package.json', undefined, 1, undefined, false)
/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:301 [Extension Host] [GitLens] Add log cache for 'w:/work/github/vscode.git/package.json:log:n1'
/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:301 [Extension Host] [GitLens] git -c core.quotepath=false log --name-status --full-history -M --date=iso8601 --format=%H -%nauthor %an%nauthor-date %ai%nparents %P%nsummary %B%nfilename ? --follow -n1 --no-merges -- package.json   cwd='w:/work/github/vscode.git'
/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:301 [Extension Host] [GitLens] Not Cached(blame): getBlameForFile('w:/work/github/vscode.git/', '', undefined)
/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:301 [Extension Host] [GitLens] Add blame cache for ':blame'
/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:301 [Extension Host] [GitLens] Skipping blame; '' is gitignored
/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:301 [Extension Host] [GitLens] Cached(log:n1): getLogForFile('undefined', 'w:\work\github\vscode.git\package.json', undefined, 1, undefined, false)
/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:301 [Extension Host] [GitLens] Cached(blame): getBlameForFile('w:/work/github/vscode.git/', '', undefined)
/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:301 [Extension Host] [GitLens] getBlameForLine('w:/work/github/vscode.git/', '', 46, undefined)
/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:301 [Extension Host] [GitLens] Cached(blame): getBlameForFile('w:/work/github/vscode.git/', '', undefined)
```

**Comment by vvs** [comment]
Looking at the debug output, it seems that the extension is not getting the actual file names to work with. It gets just '', and naturally doesn't provide any of its services for such a file.

**Comment by eamodio** [comment]
@vvs Thank you so much for your deep investigation! It looks like vscode has fixed the underlying issue. Once the next insiders comes out we can verify that is the case.

**Comment by vvs** [comment]
I've built VS Code from the latest master sources (which supposed to have the fix) and unfortunately, that fix for Microsoft/vscode#31038 didn't fix this issue.

Most of the Git Lens functionality continues to be disabled and not available.

Sometimes I see the following error when launching VS Code (freshly built from latest master, Microsoft/vscode@167d697f6d972a ):
```
Cannot read property 'length' of undefined: TypeError: Cannot read property 'length' of undefined
    at file:///W:/work/github/vscode.git/out/vs/platform/actions/common/menu.js:45:64
    at CallbackList.invoke (file:///W:/work/github/vscode.git/out/vs/base/common/callbackList.js:58:43)
    at Emitter.fire (file:///W:/work/github/vscode.git/out/vs/base/common/event.js:91:40)
    at file:///W:/work/github/vscode.git/out/vs/base/common/event.js:294:37
```

**Comment by vvs** [comment]
The fresh log, is a bit different from the one originally reported. Now I see that Git Lens could get the file name for the git log caching, but not for the git blame though.

```
[Extension Host] debugger listening on port 5870
/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:300 [Extension Host] [GitLens] GitLens(v4.3.1) active: w:/work/github/vscode.git
/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:300 [Extension Host] [GitLens] Git found: 2.13.3.windows.1.13.gaf0c2223da @ W:\re\git\cmd\git.exe
/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:300 [Extension Host] [GitLens] git -c core.quotepath=false rev-parse --show-toplevel   cwd='w:/work/github/vscode.git'
/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:300 [Extension Host] [GitLens] Git version: 2.13.3.windows.1.13.gaf0c2223da
/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:300 [Extension Host] [GitLens] CodeLens config changed; resetting CodeLens provider
/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:300 [Extension Host] [GitLens] Not Cached(log:n1): getLogForFile('undefined', 'w:\work\github\vscode.git\package.json', undefined, 1, undefined, false)
/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:300 [Extension Host] [GitLens] Add log cache for 'w:/work/github/vscode.git/package.json:log:n1'
2/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:300 [Extension Host] [GitLens] Cached(log:n1): getLogForFile('undefined', 'w:\work\github\vscode.git\package.json', undefined, 1, undefined, false)
/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:300 [Extension Host] [GitLens] git -c core.quotepath=false log --name-status --full-history -M --date=iso8601 --format=%H -%nauthor %an%nauthor-date %ai%nparents %P%nsummary %B%nfilename ? --follow -n1 --no-merges -- package.json   cwd='w:/work/github/vscode.git'
2/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:300 [Extension Host] [GitLens] getRemotes('w:/work/github/vscode.git')
/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:300 [Extension Host] [GitLens] Not Cached(blame): getBlameForFile('w:/work/github/vscode.git/', '', undefined)
/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:300 [Extension Host] [GitLens] Add blame cache for ':blame'
/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:300 [Extension Host] [GitLens] Skipping blame; '' is gitignored
2/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:300 [Extension Host] [GitLens] git -c core.quotepath=false remote -v   cwd='w:/work/github/vscode.git'
/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:300 [Extension Host] [GitLens] getStash('w:/work/github/vscode.git')
/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:300 [Extension Host] [GitLens] Cached(log:n1): getLogForFile('undefined', 'w:\work\github\vscode.git\package.json', undefined, 1, undefined, false)
/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:300 [Extension Host] [GitLens] Cached(blame): getBlameForFile('w:/work/github/vscode.git/', '', undefined)
/W:/work/github/vscode.git/out/vs/workbench/electron-browser/extensionHost.js:300 [Extension Host] [GitLens] git -c core.quotepath=false stash list --name-status --full-history -M --format=%H -%nauthor-date %ai%nreflog-selector %gd%nsummary %B%nfilename ?   cwd='w:/work/github/vscode.git'
```

**Comment by lolmaus** [comment]
I've updated to:
VS Code: 1.26.0-insider (2018-08-03)
GitLens: 8.5.4 (2018-07-31)

No GitLens UI is available to me. Command "Show GitLens" does nothing.

**Comment by vvs** [comment]
@lolmaus, FWIW, everything works just fine for me on Windows 10 x64, latest insiders.

**Comment by lolmaus** [comment]
@vvs I'm happy for you, but it doesn't help me resolve my issue.

Can I provide debugging info or something?

**Comment by eamodio** [comment]
@lolmaus can you open a new issue for this and attach logs (the new issue template walks you through it). Also are you seeing the GitLens icon in the activity bar? Could you possibly be in Zen mode?

**Comment by lolmaus** [comment]
@eamodio Another VS Code Insiders update came, and GitLens is back! 

![image](https://user-images.githubusercontent.com/200884/43718172-81f019ae-9992-11e8-9a55-5b4761d1f4cd.png)

**Comment by neolivz** [comment]
And it's gone again :(
