### ISSUE TITLE
Crashing VSCode Extension Host

### ISSUE THREAD

**Issue by JCKodel** [eamodio/vscode-gitlens#1207]
- GitLens Version: 11.0.5
- Git Version: `run git --version` 2.28.0

- VSCode Version: `run code --version` 1.51.1, e5a624b788d92b8d34d1392e4c4d9789406efe8f, x64
- OS Version: MacOS 10.15.7

Steps to Reproduce:

1. Actually, nothing

Often, VSCode shows a notification about VSCode Extension Host crashing, and a button to open the DevTools.

On DevTools, there is this:

```
/Users/jckodel/.vscode/extensions/eamodio.gitlens-11.0.5/dist/gitlens.js:2
module.exports=(()=>{var e,t,i,n={7484:function(e){e.exports=function(){var e="millisecond",t="second",i="minute",n="hour",o="day",r="week",s="month",a="quarter",l="year",c="date",h=/^(\d{4})[-/]?(\d{1,2})?[-/]?(\d{0,2})[^0-9]*(\d{1,2})?:?(\d{1,2})?:?(\d{1,2})?.?(\d+)?$/,u=/\[([^\]]+)]|Y{2,4}|M{1,4}|D{1,2}|d{1,4}|H{1,2}|h{1,2}|a|A|m{1,2}|s{1,2}|Z{1,2}|SSS/g,d={name:"en",weekdays:"Sunday_Monday_Tuesday_Wednesday_Thursday_Friday_Saturday".split("_"),months:"January_February_March_April_May_June_July_August_September_October_November_December".split("_")},m=function(e,t,i){var n=String(e);return!n||n.length>=t?e:""+Array(t+1-n.length).join(i)+e},p={s:m,z:function(e){var t=-e.utcOffset(),i=Math.abs(t),n=Math.floor(i/60),o=i%60;return(t<=0?"+":"-")+m(n,2,"0")+":"+m(o,2,"0")},m:function e(t,i){if(t.date()<i.date())return-e(i,t);var n=12*(i.year()-t.year())+(i.month()-t.month()),o=t.clone().add(n,s),r=i-o<0,a=t.clone().add(n+(r?-1:1),s);ret

[TypeError: t.trim is not a function
	at new RunError (/Users/jckodel/.vscode/extensions/eamodio.gitlens-11.0.5/dist/gitlens.js:2:821249)
	at /Users/jckodel/.vscode/extensions/eamodio.gitlens-11.0.5/dist/gitlens.js:2:821789
	at exithandler (child_process.js:311:5)
	at ChildProcess.errorhandler (child_process.js:323:5)
	at ChildProcess.emit (events.js:223:5)
	at ChildProcess.EventEmitter.emit (domain.js:475:20)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:81:21)]
```

**Comment by eamodio** [comment]
Hrm, I haven't seen that before. Could you try uninstalling GitLens and then reinstalling (making sure to restart VS Code between uninstall/install). Maybe something is corrupted. 

If that still doesn't help, please enable output channel logging by setting `"gitlens.outputLevel": "debug"` in your settings. This will enable logging to the *GitLens* channel in the *Output* pane. Once enabled, please reproduce the issue and attach the log from the *GitLens* channel.

**Comment by JCKodel** [comment]
After rebooting to install Big Sur this bug went away. I guess it was some kind of corruption fixed by a reboot.
