### ISSUE TITLE
Remote containers: cannot activate extension (TypeError: e.globalState.setKeysForSync is not a function)

### ISSUE THREAD

**Issue by technodrome** [eamodio/vscode-gitlens#1251]
- GitLens Version: 11.0.6
- Git Version: 2.26.2
- VSCode Version: 1.51.0-insider
- OS Version: Linux x64 5.4.80-2-MANJARO

Steps to Reproduce:

1. When developing in a remote container, GitLens is installed in the container. Its commands are available in the command palette but when clicked on `Welcome` or `Set Views Layout`, an error message pops up. Output from Remote Extension Host shows:

```
[2020-12-08 18:39:58.228] [exthost] [info] ExtensionService#_doActivateExtension eamodio.gitlens {"startup":false,"extensionId":{"value":"eamodio.gitlens","_lower":"eamodio.gitlens"},"activationEvent":"onStartupFinished"}
[2020-12-08 18:39:58.229] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/vscode/.vscode-server-insiders/extensions/eamodio.gitlens-11.0.6/dist/gitlens
[2020-12-08 18:39:58.463] [exthost] [info] eager extensions activated
[2020-12-08 18:39:58.521] [exthost] [error] Activating extension eamodio.gitlens failed due to an error:
[2020-12-08 18:39:58.525] [exthost] [error] TypeError: e.globalState.setKeysForSync is not a function
	at f (/home/vscode/.vscode-server-insiders/extensions/eamodio.gitlens-11.0.6/dist/gitlens.js:2:626729)
	at Function._callActivateOptional (/home/vscode/.vscode-server-insiders/bin/a522f37e37735c0cbe7244680250ef73d9054dd1/out/vs/server/remoteExtensionHostProcess.js:955:841)
	at Function._callActivate (/home/vscode/.vscode-server-insiders/bin/a522f37e37735c0cbe7244680250ef73d9054dd1/out/vs/server/remoteExtensionHostProcess.js:955:492)
	at /home/vscode/.vscode-server-insiders/bin/a522f37e37735c0cbe7244680250ef73d9054dd1/out/vs/server/remoteExtensionHostProcess.js:953:841
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Promise.all (index 0)
```
Is this just a bug or GitLens does not work properly when used in combination with a remote container?

**Comment by eamodio** [comment]
@sandy081 any idea on this?

**Comment by sandy081** [comment]
Seems that specific VS Code version `1.51.0-insider` does not have the `e.globalState.setKeysForSync` API.

**Comment by eamodio** [comment]
Ah, I missed that it was the insiders version.

@technodrome Please update to the latest insiders or switch to the stable version of 1.51.
