### ISSUE TITLE
Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by tiansin** [eamodio/vscode-gitlens#252]
- GitLens Version:7.5.5
- VSCode Version:1.9.2
- OS Version:Windows10

Steps to Reproduce:

1. Start vscode report error.

```
Cannot read property 'push' of undefined: TypeError: Cannot read property 'push' of undefined
	at xi.<anonymous> (C:\Users\xfx\.vscode\extensions\eamodio.gitlens-7.5.5\out\extension.js:1:120804)
	at Generator.next (<anonymous>)
	at fulfilled (C:\Users\xfx\.vscode\extensions\eamodio.gitlens-7.5.5\node_modules\tslib\tslib.js:102:62)
	at <anonymous>
```

Sorry, it happened only once and I did not get any more information.

**Comment by s1awek** [comment]
Still got above problem:

- GitLens Version: 8.4
- VSCode Version: 1.24.1
- OS Version: Windows 10

Steps to reproduce:

1. Click gitlens icon on left side menu (or ctrl+shif+g)
2. Using built-in terminal checkout to any branch (eg. git checkout master)

Result:

`Error: Cannot read property 'push' of undefined
	at ci.getChildren (C:\[private]\.vscode\extensions\eamodio.gitlens-8.4.1\out\extension.js:1:131819)`

`  ERR Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined
	at QualityOfLife.onChangeEditorHandler (C:\[private]\.vscode\extensions\hvyindustries.crane-0.3.8\out\src\features\qualityOfLife.js:29:19)
	at QualityOfLife.vscode.window.onDidChangeActiveTextEditor.editor (C:\[private]\.vscode\extensions\hvyindustries.crane-0.3.8\out\src\features\qualityOfLife.js:16:68)
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:764)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:727:112
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:764)
	at e.$acceptDocumentsAndEditorsDelta (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:725:330)
	at e._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:636:832)
	at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:636:550)
	at e._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:631)
	at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:400)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:634:315
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:637:395
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:95:432
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:764)
	at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:338)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)`

**Comment by eamodio** [comment]
@s1awek is this still happening for you?

**Comment by s1awek** [comment]
@eamodio Yes, still got this problem.
