### ISSUE TITLE
Running the contributed command:'gitlens.toggleBlame' failed.

### ISSUE THREAD

**Issue by felixfbecker** [eamodio/vscode-gitlens#3]
Stack trace in console:
```
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:121 Path must be a string. Received undefined: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.relative (path.js:576:5)
    at Function.Git.normalizePath (C:\Users\felix\.vscode\extensions\eamodio.gitlens-0.0.5\out\src\git.js:19:53)
    at GitProvider.getBlameForFile (C:\Users\felix\.vscode\extensions\eamodio.gitlens-0.0.5\out\src\gitProvider.js:58:34)
    at GitCodeLensProvider.provideCodeLenses (C:\Users\felix\.vscode\extensions\eamodio.gitlens-0.0.5\out\src\gitCodeLensProvider.js:54:45)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:11:28014
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:22775
    at new n.Class.derive._oncancel (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:5:26897)
    at Object.l [as asWinJsPromise] (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:6:22738)
    at e.provideCodeLenses (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:11:27968)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:12:5839
    at t._withAdapter (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:12:5149)
    at t.$provideCodeLenses (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:12:5801)
    at t.e.handle (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:10:22905)
    at s (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:7:30449)
    at p (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:7:31126)
```

**Comment by eamodio** [comment]
@felixfbecker Please try again with 0.0.6 it has much better logging of errors.

**Comment by eamodio** [comment]
@felixfbecker closing. Please re-open if it is still an issue.
