### ISSUE TITLE
Line History - Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by turijs** [eamodio/vscode-gitlens#568]
Issue Type: <b>Bug</b>

Certain lines of files in my repo are causing this error to occur, which always coincides with the Line History Explorer displaying 0 commits. Full stack trace is below.
```
Error: Cannot read property 'startsWith' of undefined
	at Function.resolve (/home/turi/.vscode/extensions/eamodio.gitlens-9.0.1/dist/extension.js:1:279901)
	at Function.resolveToUri (/home/turi/.vscode/extensions/eamodio.gitlens-9.0.1/dist/extension.js:1:280003)
	at Function.fromFile (/home/turi/.vscode/extensions/eamodio.gitlens-9.0.1/dist/extension.js:1:278303)
	at new commitFileNode_CommitFileNode (/home/turi/.vscode/extensions/eamodio.gitlens-9.0.1/dist/extension.js:1:437317)
	at e.push.Be.filterMap.e (/home/turi/.vscode/extensions/eamodio.gitlens-9.0.1/dist/extension.js:1:476926)
	at Object.e.filterMap (/home/turi/.vscode/extensions/eamodio.gitlens-9.0.1/dist/extension.js:1:243498)
	at e.filterMap.next (<anonymous>)
	at Ei (/home/turi/.vscode/extensions/eamodio.gitlens-9.0.1/dist/extension.js:1:445607)
	at Ei.next (<anonymous>)
	at lineHistoryNode_LineHistoryNode.getChildren (/home/turi/.vscode/extensions/eamodio.gitlens-9.0.1/dist/extension.js:1:476880)
	at <anonymous>
t.onDidNotificationChange @ notificationsAlerts.ts:38
(anonymous) @ notificationsAlerts.ts:26
e.fire @ event.ts:145
t.notify @ notifications.ts:113
t.error @ notificationService.ts:48
(anonymous) @ mainThreadTreeViews.ts:142
v @ winjs.base.js:1230
enter @ winjs.base.js:916
_run @ winjs.base.js:1089
_error @ winjs.base.js:1062
e.resolveErr @ lazyPromise.ts:71
t._receiveReplyErr @ rpcProtocol.ts:419
t._receiveOneMessage @ rpcProtocol.ts:316
(anonymous) @ rpcProtocol.ts:146
e.fire @ event.ts:145
a @ ipc.net.ts:103
n._socketDataListener @ ipc.net.ts:132
emitOne @ events.js:116
emit @ events.js:211
addChunk @ _stream_readable.js:263
readableAddChunk @ _stream_readable.js:250
Readable.push @ _stream_readable.js:208
onread @ net.js:594
```

Extension version: 9.0.1
VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:07:43.495Z)
OS version: Linux x64 4.15.0-42-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz (4 x 2490)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|5.70GB (0.38GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by eamodio** [comment]
@turijs Unfortunately I can't seem to reproduce this and even though I can see the surface cause of the exception, I can't see the root cause.

Can you please enable output channel logging by setting `"gitlens.outputLevel": "debug"` in your `settings.json`. This will enable logging to the *GitLens* channel in the *Output* pane. Once enabled, please reproduce the issue (if possible) and attach the log lines from the *GitLens* channel.

**Comment by turijs** [comment]
@eamodio Thanks for taking a look! I have done as you said and the output is below for when I clicked into the problematic line (I replaced paths with placeholders since it is a private repo):
```
[2018-12-05 17:46:00:031] [a5] GitService.getBlameForLine — e=GitUri(file:///absolute/path/to/file repoPath=/absolute/path/to/repo), t=212
[2018-12-05 17:46:00:031] [a6] GitService.getBlameForFile — e=GitUri(file:///absolute/path/to/file repoPath=/absolute/path/to/repo)
[2018-12-05 17:46:00:031] [a6] GitService.getBlameForFile Cache hit: 'blame'
[2018-12-05 17:46:00:032] [a6] GitService.getBlameForFile completed • 0 ms
[2018-12-05 17:46:00:032] [a5] GitService.getBlameForLine completed • 0 ms
[2018-12-05 17:46:00:282] [a7] LineHistoryTrackerNode.onActiveLinesChanged
[2018-12-05 17:46:00:283] [a8] LineHistoryTrackerNode.triggerChange
[2018-12-05 17:46:00:283] [a9] LineHistoryView.refreshNode — e=LineHistoryTrackerNode
[2018-12-05 17:46:00:283] [aa] LineHistoryTrackerNode.refresh
[2018-12-05 17:46:00:283] [ab] GitService.getRepoPath — e=Uri(file:///absolute/path/to/file)
[2018-12-05 17:46:00:283] [ac] GitService.getRepository — e=Uri(file:///absolute/path/to/file), t={"skipCacheUpdate":true}
[2018-12-05 17:46:00:284] [a7] LineHistoryTrackerNode.onActiveLinesChanged completed • 0 ms
[2018-12-05 17:46:00:284] [ad] GitService.isTracked true • 0 ms — e=/absolute/path/to/file, t=/absolute/path/to/repo, i={"skipCacheUpdate":true}
[2018-12-05 17:46:00:284] [ac] GitService.getRepository completed • 0 ms
[2018-12-05 17:46:00:284] [ab] GitService.getRepoPath completed • 0 ms
[2018-12-05 17:46:00:284] [ae] LineHistoryTrackerNode.resetChild
[2018-12-05 17:46:00:284] [af] LineHistoryNode.dispose
[2018-12-05 17:46:00:284] [b0] LineHistoryNode.unsubscribe
[2018-12-05 17:46:00:284] [af] LineHistoryNode.dispose completed • 0 ms
[2018-12-05 17:46:00:285] [ae] LineHistoryTrackerNode.resetChild completed • 0 ms
[2018-12-05 17:46:00:285] [aa] LineHistoryTrackerNode.refresh completed • 1 ms
[2018-12-05 17:46:00:285] [b0] LineHistoryNode.unsubscribe completed • 0 ms
[2018-12-05 17:46:00:285] [b1] LineHistoryView.triggerNodeChange — e=LineHistoryTrackerNode
[2018-12-05 17:46:00:285] [b1] LineHistoryView.triggerNodeChange completed • 0 msb
[2018-12-05 17:46:00:285] [a9] LineHistoryView.refreshNode completed • 2 ms
[2018-12-05 17:46:00:285] [a8] LineHistoryTrackerNode.triggerChange completed • 2 ms
[2018-12-05 17:46:00:487] [b2] LineHistoryNode.ensureSubscription
[2018-12-05 17:46:00:488] [b3] LineHistoryNode.subscribe
[2018-12-05 17:46:00:488] [b4] GitService.getRepository — e=GitUri(file:///absolute/path/to/file repoPath=/absolute/path/to/repo)
[2018-12-05 17:46:00:488] [b4] GitService.getRepository completed • 0 ms
[2018-12-05 17:46:00:488] [b3] LineHistoryNode.subscribe completed • 0 ms
[2018-12-05 17:46:00:489] [b2] LineHistoryNode.ensureSubscription completed • 0 ms
[2018-12-05 17:46:00:497] [b5] GitService.getLogForFile — e=/absolute/path/to/repo, t=/absolute/path/to/file, i={"range":{"start":{"line":212,"character":39},"end":{"line":212,"character":39},"active":{"line":212,"character":39},"anchor":{"line":212,"character":39}}}
[2018-12-05 17:46:00:498] [b6] GitService.isTracked true • 0 ms — e=/absolute/path/to/file, t=/absolute/path/to/repo, i={}
[2018-12-05 17:46:00:804] [/absolute/path/to/repo] git log --name-status --format=%x3c%x2ff%x3e%n%x3cr%x3e%x20%H%n%x3ca%x3e%x20%aN%n%x3ce%x3e%x20%aE%n%x3cd%x3e%x20%at%n%x3cc%x3e%x20%ct%n%x3cp%x3e%x20%P%n%x3cs%x3e%n%B%n%x3c%x2fs%x3e%n%x3cf%x3e -n50 -L 213,213:relative/path/to/file -- relative/path/to/file • 305 ms 
[2018-12-05 17:46:00:805] [b7] GitService.getCurrentUser — e=/absolute/path/to/repo
[2018-12-05 17:46:00:805] [b7] GitService.getCurrentUser completed • 0 ms
[2018-12-05 17:46:00:806] [b5] GitService.getLogForFile completed • 308 ms
[2018-12-05 17:46:33:004] [b8] RepositoryNode(gitlens:repository(/absolute/path/to/repo)).updateLastFetched
[2018-12-05 17:46:33:005] [b8] RepositoryNode(gitlens:repository(/absolute/path/to/repo)).updateLastFetched completed • 0 ms
[2018-12-05 17:47:33:006] [b9] RepositoryNode(gitlens:repository(/absolute/path/to/repo)).updateLastFetched
[2018-12-05 17:47:33:006] [b9] RepositoryNode(gitlens:repository(/absolute/path/to/repo)).updateLastFetched completed • 0 ms
```

**Comment by turijs** [comment]
@eamodio Unfortunately I don't think I can do that as the code is my company's IP and I am under an NDA. I will say that the output appeared normal at first glance. Is there a function in the gitlens codebase which parses the output of the above command where you think the problem could be arising? If so, maybe you could point me there and I could do a bit of testing to try and figure out what's going on. BTW, it's not only the one file where I've seen this happen, but I haven't been able to identify a pattern yet. Thanks again!

**Comment by turijs** [comment]
@eamodio I was looking at this again today and I am no longer able to produce the issue (tried same files/lines as before). Was it fixed? At any rate, this can probably be closed now. Thanks!

**Comment by eamodio** [comment]
I did make some changes, but couldn't be sure it fixed things. Looks like maybe they did -- thanks!
